CREATE TABLE [dbo].[Tag]
(
	[TagId] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[ArticleId] INT,
	[Content] NVARCHAR(100)
)
GO

CREATE INDEX TIndex
ON Tag (ArticleId)
GO

ALTER TABLE Tag
ADD CONSTRAINT FK_Article_Keyword_CAS
FOREIGN KEY (ArticleId) REFERENCES Article(ArticleId) ON DELETE CASCADE
GO

--Backup
CREATE TRIGGER trg_backupTag ON Tag
INSTEAD OF DELETE
AS
BEGIN
	INSERT INTO Backup_Tag 
	SELECT * 
	FROM DELETED
END
GO